/**
 * Game Assets Registry & Catalog
 * Strictly mapped to curated 2D chibi assets in public/assets/game/
 * Verified paths, dimensions, aspect ratios, and semantic usage.
 */

export const ASSET_CATALOG_METADATA = {
  // HUD
  hud: {
    coin: { path: '/assets/game/props/coin_stack.png', width: 240, height: 170, usage: 'Currency token in top HUD' },
    rating: { path: '/assets/game/props/heart_icon.png', width: 180, height: 155, usage: 'Customer satisfaction & store rating' },
    reputation: { path: '/assets/game/ui/badge_new.png', width: 158, height: 158, usage: 'Store level & reputation badge' },
    time: { path: '/assets/game/ui/counter_coin.png', width: 240, height: 160, usage: 'Timer & day cycle indicator' },
    sound: { path: '/assets/game/props/red_lantern.png', width: 160, height: 260, usage: 'Cozy red lantern sound toggle' },
    settings: { path: '/assets/game/props/menu_sign.png', width: 240, height: 260, usage: 'Wooden sign for settings modal' },
  },
  // Navigation & Action Dock
  navigation: {
    restaurant: { path: '/assets/game/props/food_stall.png', width: 385, height: 376, usage: 'Restaurant scene focus' },
    kitchen: { path: '/assets/game/props/cooking_pot.png', width: 374, height: 241, usage: 'Kitchen drawer & cooking stations' },
    delivery: { path: '/assets/game/props/delivery_crate.png', width: 277, height: 213, usage: 'Delivery drawer & online shipper orders' },
    menu: { path: '/assets/game/ui/sign_menu.png', width: 268, height: 140, usage: 'Menu modal & recipes' },
    inventory: { path: '/assets/game/props/veggie_basket.png', width: 414, height: 322, usage: 'Morning market & ingredient stock' },
    upgrade: { path: '/assets/game/ui/badge_new.png', width: 158, height: 158, usage: 'Restaurant equipment upgrades' },
    settings: { path: '/assets/game/props/menu_sign.png', width: 240, height: 260, usage: 'Settings modal' },
  },
  // User Actions
  actions: {
    serve: { path: '/assets/game/props/rice_bowl.png', width: 280, height: 190, usage: 'Deliver prepared dish to customer' },
    close: { path: '/assets/game/ui/icon_close.png', width: 149, height: 127, usage: 'Close drawer or modal' },
    plus: { path: '/assets/game/ui/icon_plus.png', width: 131, height: 128, usage: 'Increment quantity / spice level' },
    minus: { path: '/assets/game/ui/icon_minus.png', width: 119, height: 123, usage: 'Decrement quantity / spice level' },
    start: { path: '/assets/game/ui/btn_start.png', width: 264, height: 102, usage: 'Start new day / open restaurant' },
    complete: { path: '/assets/game/ui/btn_complete.png', width: 225, height: 101, usage: 'Finish cooking / confirm order' },
    back: { path: '/assets/game/ui/btn_back.png', width: 210, height: 95, usage: 'Back / return' },
    lock: { path: '/assets/game/ui/btn_lock.png', width: 216, height: 100, usage: 'Locked feature indicator' },
    unlock: { path: '/assets/game/ui/btn_unlock.png', width: 214, height: 98, usage: 'Unlock item action' },
    buy: { path: '/assets/game/ui/btn_buy_cart.png', width: 216, height: 101, usage: 'Buy ingredient at market' },
  }
} as const;

export const GAME_ASSETS = {
  hud: {
    coin: '/assets/game/props/coin_stack.png',
    rating: '/assets/game/props/heart_icon.png',
    heart: '/assets/game/props/heart_icon.png',
    reputation: '/assets/game/ui/badge_new.png',
    time: '/assets/game/props/coin_stack.png',
    sound: '/assets/game/props/red_lantern.png',
    settings: '/assets/game/props/menu_sign.png',
  },

  navigation: {
    restaurant: '/assets/game/props/food_stall.png',
    kitchen: '/assets/game/props/cooking_pot.png',
    delivery: '/assets/game/props/delivery_crate.png',
    menu: '/assets/game/ui/sign_menu.png',
    inventory: '/assets/game/props/veggie_basket.png',
    upgrade: '/assets/game/ui/badge_new.png',
    settings: '/assets/game/props/menu_sign.png',
  },

  actions: {
    serve: '/assets/game/props/rice_bowl.png',
    close: '/assets/game/ui/icon_close.png',
    plus: '/assets/game/ui/icon_plus.png',
    minus: '/assets/game/ui/icon_minus.png',
    start: '/assets/game/props/food_stall.png',
    complete: '/assets/game/props/rice_bowl.png',
    back: '/assets/game/ui/icon_close.png',
    lock: '/assets/game/ui/badge_new.png',
    unlock: '/assets/game/ui/btn_unlock.png',
    buy: '/assets/game/ui/btn_buy_cart.png',
  },

  food: {
    ramyeon: '/assets/game/dishes/ramyeon.png',
    spicy_ramyeon: '/assets/game/dishes/ramyeon.png',
    tokbokki: '/assets/game/dishes/tokbokki.png',
    cheese_tokbokki: '/assets/game/dishes/tokbokki.png',
    kimbap: '/assets/game/dishes/kimbap.png',
    kimbap_classic: '/assets/game/dishes/kimbap.png',
    kimbap_cheese: '/assets/game/dishes/kimbap.png',
    canh_kimchi: '/assets/game/dishes/canh_kimchi.png',
    ga_ran_han_quoc: '/assets/game/dishes/ga_ran_han_quoc.png',
    bibimbap: '/assets/game/dishes/bibimbap.png',
    pho_mai_que: '/assets/game/dishes/pho_mai_que.png',
    mandu: '/assets/game/dishes/mandu.png',
    banh_xeo_han: '/assets/game/dishes/banh_xeo_han.png',
    pho_bo: '/assets/game/dishes/pho_bo.png',
    com_nam: '/assets/game/dishes/com_nam.png',
    tra_dao: '/assets/game/dishes/tra_dao.png',
    banana_milk: '/assets/game/props/drinks_carrier.png',
  },

  dishes: {
    ramyeon: '/assets/game/dishes/ramyeon.png',
    spicy_ramyeon: '/assets/game/dishes/ramyeon.png',
    tokbokki: '/assets/game/dishes/tokbokki.png',
    cheese_tokbokki: '/assets/game/dishes/tokbokki.png',
    kimbap: '/assets/game/dishes/kimbap.png',
    kimbap_classic: '/assets/game/dishes/kimbap.png',
    kimbap_cheese: '/assets/game/dishes/kimbap.png',
    canh_kimchi: '/assets/game/dishes/canh_kimchi.png',
    ga_ran_han_quoc: '/assets/game/dishes/ga_ran_han_quoc.png',
    bibimbap: '/assets/game/dishes/bibimbap.png',
    pho_mai_que: '/assets/game/dishes/pho_mai_que.png',
    mandu: '/assets/game/dishes/mandu.png',
    banh_xeo_han: '/assets/game/dishes/banh_xeo_han.png',
    pho_bo: '/assets/game/dishes/pho_bo.png',
    com_nam: '/assets/game/dishes/com_nam.png',
    tra_dao: '/assets/game/dishes/tra_dao.png',
    banana_milk: '/assets/game/props/drinks_carrier.png',
  },

  toppings: {
    beef: '/assets/game/dishes/pho_bo.png',
    sausage: '/assets/game/ingredients/xuc_xich.png',
    kimchi: '/assets/game/ingredients/bap_cai_kimchi.png',
    egg: '/assets/game/ingredients/trung.png',
    mushroom: '/assets/game/ingredients/nam.png',
    spinach: '/assets/game/ingredients/cai_bo_xoi.png',
    cheese: '/assets/game/ingredients/pho_mai_lat.png',
    fish_cake: '/assets/game/ingredients/cha_ca.png',
    scallion: '/assets/game/ingredients/hanh_la.png',
    chilli: '/assets/game/ingredients/ot_do.png',
    rice_cake: '/assets/game/ingredients/banh_gao.png',
    carrot: '/assets/game/ingredients/ca_rot.png',
    cucumber: '/assets/game/ingredients/dua_leo.png',
    sesame: '/assets/game/ingredients/me_rang.png',
    seaweed: '/assets/game/ingredients/rong_bien.png',
  },

  ingredients: {
    mi_ramyeon: '/assets/game/ingredients/mi_ramyeon.png',
    banh_gao: '/assets/game/ingredients/banh_gao.png',
    bap_cai_kimchi: '/assets/game/ingredients/bap_cai_kimchi.png',
    xuc_xich: '/assets/game/ingredients/xuc_xich.png',
    trung: '/assets/game/ingredients/trung.png',
    nam: '/assets/game/ingredients/nam.png',
    pho_mai_lat: '/assets/game/ingredients/pho_mai_lat.png',
    cha_ca: '/assets/game/ingredients/cha_ca.png',
    cai_bo_xoi: '/assets/game/ingredients/cai_bo_xoi.png',
    hanh_la: '/assets/game/ingredients/hanh_la.png',
    ca_rot: '/assets/game/ingredients/ca_rot.png',
    dua_leo: '/assets/game/ingredients/dua_leo.png',
    ot_do: '/assets/game/ingredients/ot_do.png',
    nuoc_dung: '/assets/game/ingredients/nuoc_dung.png',
    tuong_ot_gochujang: '/assets/game/ingredients/tuong_ot_gochujang.png',
    nuoc_tuong: '/assets/game/ingredients/nuoc_tuong.png',
    duong: '/assets/game/ingredients/duong.png',
    toi: '/assets/game/ingredients/toi.png',
    rong_bien: '/assets/game/ingredients/rong_bien.png',
    me_rang: '/assets/game/ingredients/me_rang.png',
    beef: '/assets/game/dishes/pho_bo.png',
    rice: '/assets/game/props/rice_sack.png',
    banana_milk_carton: '/assets/game/props/drinks_carrier.png',
  },

  cooking: {
    pot: '/assets/game/props/cooking_pot.png',
    bowl: '/assets/game/props/rice_bowl.png',
    pan: '/assets/game/props/frying_pan.png',
    board: '/assets/game/props/cutting_board.png',
    stove: '/assets/game/props/gas_stove.png',
    knife: '/assets/game/props/kitchen_knife.png',
    ladle: '/assets/game/props/ladle.png',
    tray: '/assets/game/props/condiment_tray.png',
    takeaway_box: '/assets/game/props/takeaway_boxes.png',
    crate: '/assets/game/props/delivery_crate.png',
  },

  props: {
    cooking_pot: '/assets/game/props/cooking_pot.png',
    frying_pan: '/assets/game/props/frying_pan.png',
    cutting_board: '/assets/game/props/cutting_board.png',
    rice_bowl: '/assets/game/props/rice_bowl.png',
    gas_stove: '/assets/game/props/gas_stove.png',
    kitchen_knife: '/assets/game/props/kitchen_knife.png',
    ladle: '/assets/game/props/ladle.png',
    condiment_tray: '/assets/game/props/condiment_tray.png',
    takeaway_boxes: '/assets/game/props/takeaway_boxes.png',
    delivery_crate: '/assets/game/props/delivery_crate.png',
    drinks_carrier: '/assets/game/props/drinks_carrier.png',
    rice_sack: '/assets/game/props/rice_sack.png',
    veggie_basket: '/assets/game/props/veggie_basket.png',
    egg_basket: '/assets/game/props/egg_basket.png',
    food_stall: '/assets/game/props/food_stall.png',
    herb_plant: '/assets/game/props/herb_plant.png',
    menu_sign: '/assets/game/props/menu_sign.png',
    red_lantern: '/assets/game/props/red_lantern.png',
    coin_stack: '/assets/game/props/coin_stack.png',
    heart_icon: '/assets/game/props/heart_icon.png',
  },

  buttons: {
    start: '/assets/game/ui/btn_start.png',
    start_alt: '/assets/game/ui/btn_start_alt.png',
    complete: '/assets/game/ui/btn_complete.png',
    complete_alt: '/assets/game/ui/btn_complete_alt.png',
    back: '/assets/game/ui/btn_back.png',
    back_alt: '/assets/game/ui/btn_back_alt.png',
    buy_coin: '/assets/game/ui/btn_buy_coin.png',
    buy_coin_alt: '/assets/game/ui/btn_buy_coin_alt.png',
    buy_cart: '/assets/game/ui/btn_buy_cart.png',
    buy_cart_disabled: '/assets/game/ui/btn_buy_cart_disabled.png',
    lock: '/assets/game/ui/btn_lock.png',
    unlock: '/assets/game/ui/btn_unlock.png',
    close: '/assets/game/ui/icon_close.png',
    plus: '/assets/game/ui/icon_plus.png',
    minus: '/assets/game/ui/icon_minus.png',
  },

  ui: {
    counter_coin: '/assets/game/ui/counter_coin.png',
    badge_heart: '/assets/game/ui/badge_heart.png',
    badge_star: '/assets/game/ui/badge_new.png',
    badge_new: '/assets/game/ui/badge_new.png',
    sign_cooking: '/assets/game/ui/sign_cooking.png',
    sign_ingredient: '/assets/game/ui/sign_ingredient.png',
    sign_menu: '/assets/game/ui/sign_menu.png',
    sign_recipe: '/assets/game/ui/sign_recipe.png',
    step_1: '/assets/game/ui/step_1_prepare.png',
    step_2: '/assets/game/ui/step_2_cook.png',
    step_3: '/assets/game/ui/step_3_decorate.png',
    step_4: '/assets/game/ui/step_4_finish.png',
    tab_main: '/assets/game/ui/tab_main.png',
    tab_side: '/assets/game/ui/tab_side.png',
    tab_drink: '/assets/game/ui/tab_drink.png',
    tab_ingredient: '/assets/game/ui/tab_ingredient.png',
    tab_recipe: '/assets/game/ui/tab_recipe.png',
    card_kimbap: '/assets/game/ui/card_kimbap.png',
    card_banh_xeo: '/assets/game/ui/card_banh_xeo.png',
    card_pho_bo: '/assets/game/ui/card_pho_bo.png',
  },

  customers: {
    students: {
      male: '/assets/game/customers/student_male_01.png',
      female: '/assets/game/customers/student_female_01.png',
    },
    office: {
      male: '/assets/game/customers/office_male_01.png',
      female: '/assets/game/customers/office_female_01.png',
    },
    adults: {
      male_01: '/assets/game/customers/adult_male_01.png',
      male_backpack: '/assets/game/customers/adult_male_backpack_01.png',
      male_cap: '/assets/game/customers/adult_male_cap_01.png',
      female_01: '/assets/game/customers/adult_female_01.png',
      female_02: '/assets/game/customers/adult_female_02.png',
      female_03: '/assets/game/customers/adult_female_03.png',
    },
    gym: {
      male: '/assets/game/customers/gym_male_01.png',
      female: '/assets/game/customers/gym_female_01.png',
    },
    elderly: {
      male: '/assets/game/customers/elderly_male_01.png',
      female: '/assets/game/customers/elderly_female_01.png',
    },
  },

  shippers: {
    green: '/assets/game/shippers/shipper_green_01.png',
    orange: '/assets/game/shippers/shipper_orange_01.png',
  },

  backgrounds: {
    storefront: '/assets/game/backgrounds/korean_storefront.png',
    dining: '/assets/game/backgrounds/korean_dining_room.png',
    restaurant: '/assets/game/backgrounds/korean_dining_room.png',
    kitchen: '/assets/game/backgrounds/korean_kitchen.png',
  },

  effects: {
    glow: '/assets/game/ui/badge_new.png',
  },

  semanticIcons: {
    coin: '/assets/game/props/coin_stack.png',
    heart: '/assets/game/props/heart_icon.png',
    star: '/assets/game/ui/badge_new.png',
    close: '/assets/game/ui/icon_close.png',
    plus: '/assets/game/ui/icon_plus.png',
    minus: '/assets/game/ui/icon_minus.png',
    lock: '/assets/game/ui/btn_lock.png',
    unlock: '/assets/game/ui/btn_unlock.png',
    cart: '/assets/game/ui/btn_buy_cart.png',
    pot: '/assets/game/props/cooking_pot.png',
    pan: '/assets/game/props/frying_pan.png',
    bowl: '/assets/game/props/rice_bowl.png',
    board: '/assets/game/props/cutting_board.png',
    chilli: '/assets/game/ingredients/ot_do.png',
    sauce: '/assets/game/ingredients/tuong_ot_gochujang.png',
    menu: '/assets/game/ui/sign_menu.png',
    cooking: '/assets/game/ui/sign_cooking.png',
    recipe: '/assets/game/ui/sign_recipe.png',
    ingredient: '/assets/game/ui/sign_ingredient.png',
    lantern: '/assets/game/props/red_lantern.png',
    delivery: '/assets/game/props/delivery_crate.png',
    takeaway: '/assets/game/props/takeaway_boxes.png',
    knife: '/assets/game/props/kitchen_knife.png',
    gas_stove: '/assets/game/props/gas_stove.png',
    ladle: '/assets/game/props/ladle.png',
    complete: '/assets/game/ui/btn_complete.png',
    start: '/assets/game/ui/btn_start.png',
    back: '/assets/game/ui/btn_back.png',
    settings: '/assets/game/props/menu_sign.png',
    sound: '/assets/game/props/red_lantern.png',
    play: '/assets/game/ui/btn_start.png',
    pause: '/assets/game/ui/btn_back.png',
    home: '/assets/game/props/food_stall.png',
    shop: '/assets/game/ui/btn_buy_cart.png',
    upgrade: '/assets/game/ui/badge_new.png',
    serve: '/assets/game/props/rice_bowl.png',
    clock: '/assets/game/ui/badge_new.png',
    fire: '/assets/game/props/gas_stove.png',
  },
} as const;

export type SemanticIconName = keyof typeof GAME_ASSETS.semanticIcons;
